name: html_xml_parser
description: A Dart library for parsing HTML or XML into Dart objects, Map, json string and vice-versa.
version: 0.1.0
homepage: https://github.com/manojSadhu12/html_xml_parser.git
author: Manoj Sadhu <sadhu.manojkumar@gmail.com>

environment:
  sdk: '>=2.2.0 <3.0.0'

#dependencies:
#  path: ^1.4.1

dev_dependencies:
  pedantic: ^1.0.0
  test: ^1.0.0
